
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rnn-serving-python-20-20
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/relay-latency:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=50051
            - --function-name=rnn-serving-python
            - --value=French
            - --generator=random
            - --lowerBound=20
            - --upperBound=20
            - --profile-function=true
        - image: docker.io/vhiveease/rnn-serving-python:latest
          args:
            - --addr=0.0.0.0
            - --port=50051
            - --default_language=French
            - --num_strings=15
