version: '3'
services:
  relay:
    image: vhiveease/relay:latest
    platform: linux/arm64
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=parking-python
      - --function-endpoint-port=50051
      - --function-name=parking-python
    ports:
      - published: 50000
        target: 50000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
        
  parking-python-server:
    image: vhiveease/parking-python:latest
    container_name: parking-python
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  detection-1:
    image: docker.io/shixiongqi/kn-dummy
    # ports:
    #   - "50001:50001"
    container_name: detection-1
    environment:
      - SLEEP_TIME=453000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
      

  search-2:
    image: docker.io/shixiongqi/kn-dummy
    container_name: search-2
    environment:
      - SLEEP_TIME=20000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  index-3:
    image: docker.io/shixiongqi/kn-dummy
    container_name: index-3
    environment:
      - SLEEP_TIME=1000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  charging-4:
    image: docker.io/shixiongqi/kn-dummy
    container_name: charging-4
    environment:
      - SLEEP_TIME=50000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  persist-5:
    image: docker.io/shixiongqi/kn-dummy
    container_name:  persist-5
    environment:
      - SLEEP_TIME=10000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  
  parking-proxy:
    container_name: webserver
    build:
      context: ../../docker/nginxlocal/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    # entrypoint: ["/bin/sh", "-c", "./setup/nginx_setup.sh"]
    # command: /bin/sh -c "chmod +x /setup/nginx_setup.sh && setup/nginx_setup.sh"
    # command: ["/bin/sh", "-c", "apk add --no-cache curl && nginx -g 'daemon off;'"]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
