apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "453000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: search-2
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "20000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: index-3
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "1000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: charging-4
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "50000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: persist-5
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "10000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: parking-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=50051
            - --function-name=parking-python
        - image: docker.io/parking-python:latest
          # args:
          #   - --addr=0.0.0.0
          #   - --port=50051
          #   - --dataset-path=python/data/cnn_eval.json
          #   - --default_conf=cfg/default.conf
          #   - --nginx_conf=cfg/nginx.conf