name: Update Golang Dependencies

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every week at midnight UTC
  workflow_dispatch:

permissions: read-all

jobs:
  update_golang_deps:
    name: Update Golang Dependencies
    runs-on: ubuntu-latest
    env:
      GOPRIVATE_KEY: ${{ secrets.XDT_REPO_ACCESS_KEY }}
      GOPRIVATE: "github.com/ease-lab/vhive-xdt"
    steps:

      - name: Checkout code into go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - run: git config --global url."https://ease-lab:$(echo $GOPRIVATE_KEY)@github.com/ease-lab/vhive-xdt".insteadOf "https://github.com/ease-lab/vhive-xdt"

      - name: Find all go.mod files
        shell: bash
        run: |
          ./utils/update_go_dependencies.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ENABLE_AUTOMERGE_TOKEN }}
          branch: "upgrade-go-deps-on-main"
          commit-message: "Upgrade go deps"
          signoff: true
          delete-branch: true
          title: "Upgrade Golang Dependencies"
          body: |
            This Pull Request updates all the Golang dependencies 
            in all folders containing a mod file to their latest version
          base: main
          labels: |
            go
            dependencies
          add-paths: |
            *.mod
            *.sum

